defaults: &defaults
  options:
    raise_not_found_error: false

development:
  <<: *defaults
  sessions:
    default:
      hosts:
        - localhost:27017
      database: slidegate_development

test:
  <<: *defaults
  sessions:
    default:
      hosts:
        - localhost:27017
      database: slidegate_test
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  <<: *defaults
  sessions:
    default:
      hosts:
        - <%= ENV['DB_HOST'] %>
      database: <%= ENV['DB_NAME'] %>
      username: <%= ENV['DB_USER'] %>
      password: <%= ENV['DB_PASS'] %>
