defaults: &defaults
  options:
    raise_not_found_error: false

development:
  <<: *defaults
  clients:
    default:
      database: slidegate_development
      hosts:
        - localhost:27017

test:
  <<: *defaults
  clients:
    default:
      database: slidegate_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1

production:
  <<: *defaults
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - <%= ENV['DB_HOST'] %>
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PASS'] %>
